name: "release"
on:
  push:
    branches:
      - develop
jobs:
  process:
    runs-on: ubuntu-latest
    outputs:
      dependencies: ${{ steps.build.outputs.dependencies }}
    steps:
      - name: New Release
        id: build
        uses: spencerbeggs/aws-cdk-dependencies-action@v0.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: "v1.60.0"
      - name: Echo Output
        run: |
          echo ${{needs.process.outputs.dependencies}}